# pip3 install firebase_admin
# firebase - backend as a service, BaaS
import firebase_admin
from firebase_admin import credentials
from firebase_admin import db
import os

class Firebase:
    def __init__(self):
        if not firebase_admin._apps:
            # Fetch the service account key JSON file contents
            cred = credentials.Certificate(os.path.dirname(__file__) +"\serviceAccountKey.json")
            # Initialize the app with a service account, granting admin privileges
            default_app = firebase_admin.initialize_app(cred,{'databaseURL':'https://capstoneproject-4001d-default-rtdb.firebaseio.com/'})

    # Add new recipe to SysRecipe
    def Add_SysRecipe(self,scrName,scrDescription,scrDefServing,scrIngredient,scrInstruction,scrTimeReq,imageURL):
        ref = db.reference('CapstoneDatabase/')
        table_ref = ref.child('SysRecipe')
        table_ref.push({
                'scrName' : scrName,
                'scrDescription' : scrDescription,
                'scrIngredient' : scrIngredient,
                'scrInstruction' : scrInstruction,
                'scrTimeReq' : scrTimeReq,
                'imageURL' : imageURL,
                'scrDefServing' : scrDefServing
        })

        #table_ref.get().

    # Add new Item to SysIngredient
    def Add_SysIngredient(self,defItemName,analogousNames,itemType,expiry,imageURL):
        ref = db.reference('CapstoneDatabase/')
        table_ref = ref.child('SysIngredient')
        table_ref.push({
                'defItemName' : defItemName,
                'analogousNames' : analogousNames,
                'expiry' : expiry,
                'imageURL' : imageURL,
                'itemType' : itemType
        })

    def Add_WebRecipe_Unit(self,unit):
        ref = db.reference('CapstoneDatabase/WebRecipeDetail/')
        table_ref = ref.child('WebRecipe_Unit')
        table_ref.push(unit)
    
    def Add_WebRecipe_Ingredient(self,item):
        ref = db.reference('CapstoneDatabase/WebRecipeDetail/')
        table_ref = ref.child('WebRecipe_Ingredient')
        table_ref.push(item)

    def Clear_Table(self,tableName):
        db.reference('CapstoneDatabase/'+tableName+'/').delete()
    
# def Add_UserInventory_Items(defItemName):
#     UserInventory_Items = db.reference('CapstoneDatabase/SysIngredient').get()
#     for key in UserInventory_Items:
#         if(UserInventory_Items[key]["defItemName"] == defItemName):
#             print("New Item was Added")
#             return True 
#     print("Uknown Item, Unsuccesfull")
#     return False

def main():
    # delete all SysIngredient items
    fcon = Firebase()
    fcon.Clear_Table('SysIngredient')

    # pag may variation, dapat may adjective at yung root word
    # Singular yung wordings (pag s or es lang yung dulo)
    # tayo pipili ng kung ano lang lalagyan ng weight, yung may weight ay yung mga item na hindi non perishable at need maagapan yung weight
    # perishables
    pLink = "https://firebasestorage.googleapis.com/v0/b/capstoneproject-4001d.appspot.com/o/Item%20List%20Display%20%5BSysIngredient%5D%2Fperishable%20icon%20logo.jpg?alt=media&token=031a3f0e-6e26-4cfd-a4a9-41dae6c2a24f"
    npLink = "https://firebasestorage.googleapis.com/v0/b/capstoneproject-4001d.appspot.com/o/Item%20List%20Display%20%5BSysIngredient%5D%2Fnonperishable%20icon%20logo.jpg?alt=media&token=847f91cb-780d-4d22-8a22-c3e85791d318"
    # check if a whole word here is present on the websysingredient
    print("> Adding Ingredients Started")
    fcon.Add_SysIngredient("Avocado","","p","5",pLink)
    fcon.Add_SysIngredient("Egg","","p","5",pLink)
    fcon.Add_SysIngredient("Butter","","p","5",pLink)
    fcon.Add_SysIngredient("Banana Heart","Banana Blossom","p","5",pLink)
    fcon.Add_SysIngredient("Onion","","p","5",pLink)
    fcon.Add_SysIngredient("Garlic","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Belly","","p","5",pLink)
    fcon.Add_SysIngredient("Ground Pork","","p","5",pLink)
    fcon.Add_SysIngredient("Chicken Meat","","p","5",pLink)
    fcon.Add_SysIngredient("Coconut Milk","","p","5",pLink)
    fcon.Add_SysIngredient("Chili Pepper","","p","5",pLink)
    fcon.Add_SysIngredient("Shrimp","","p","5",pLink)
    fcon.Add_SysIngredient("Mussels","","p","5",pLink)
    fcon.Add_SysIngredient("Lemon","","p","5",pLink)
    fcon.Add_SysIngredient("Calamansi","","p","5",pLink)
    fcon.Add_SysIngredient("Littleneck Clam","","p","5",pLink)
    fcon.Add_SysIngredient("Fresh Milk","","p","5",pLink)
    fcon.Add_SysIngredient("Lettuce","","p","5",pLink)
    fcon.Add_SysIngredient("Lettuce Heart","","p","5",pLink)
    fcon.Add_SysIngredient("Ubod","","p","5",pLink)
    fcon.Add_SysIngredient("Carrot","","p","5",pLink)
    fcon.Add_SysIngredient("Green Beans","","p","5",pLink)
    fcon.Add_SysIngredient("Bean Sprouts","","p","5",pLink)
    fcon.Add_SysIngredient("Desiccated Coconut","","p","5",pLink)
    fcon.Add_SysIngredient("Green Onion","","p","5",pLink)
    fcon.Add_SysIngredient("Shiitake Mushroom","Shitake Mushroom","p","5",pLink)
    fcon.Add_SysIngredient("Water Chestnut","","p","5",pLink)
    fcon.Add_SysIngredient("Ginger","","p","5",pLink)
    fcon.Add_SysIngredient("Cantaloupe","","p","5",pLink)
    fcon.Add_SysIngredient("Jackfruit","Langka","p","5",pLink)
    fcon.Add_SysIngredient("Broccoli","","p","5",pLink)
    fcon.Add_SysIngredient("Red Bell Pepper","","p","5",pLink)
    fcon.Add_SysIngredient("Tomato","Roma Tomato","p","5",pLink)
    fcon.Add_SysIngredient("Sweet Pea","","p","5",pLink)
    fcon.Add_SysIngredient("Bacon","","p","5",pLink)
    fcon.Add_SysIngredient("Green Pea","","p","5",pLink)
    fcon.Add_SysIngredient("Ham","","p","5",pLink)
    fcon.Add_SysIngredient("Pineapple","","p","5",pLink)
    fcon.Add_SysIngredient("Cilantro","","p","5",pLink)
    fcon.Add_SysIngredient("Jalapeno Pepper","","p","5",pLink)
    fcon.Add_SysIngredient("Lime","","p","5",pLink)
    fcon.Add_SysIngredient("Beef Bottom Round","","p","5",pLink)
    fcon.Add_SysIngredient("Hard-Boiled Egg","","p","5",pLink)
    fcon.Add_SysIngredient("Okra","","p","5",pLink)
    fcon.Add_SysIngredient("Ground Beef","","p","5",pLink)
    fcon.Add_SysIngredient("Green Bell Pepper","","p","5",pLink)
    fcon.Add_SysIngredient("Gabi","","p","5",pLink)
    fcon.Add_SysIngredient("Radish","Labanos","p","5",pLink)
    fcon.Add_SysIngredient("Sitaw","Long Beans","p","5",pLink)
    fcon.Add_SysIngredient("Eggplant","","p","5",pLink)
    fcon.Add_SysIngredient("Banana","","p","5",pLink)
    fcon.Add_SysIngredient("Tamarind","","p","5",pLink)
    fcon.Add_SysIngredient("Bok Choy","Pak Choy","p","5",pLink)
    fcon.Add_SysIngredient("Beef Tongue","","p","5",pLink)
    fcon.Add_SysIngredient("Reserved Broth","","p","5",pLink)
    fcon.Add_SysIngredient("Catfish","","p","5",pLink)
    fcon.Add_SysIngredient("Mustard Leaves","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Hamonado Sausage","","p","5",pLink)
    fcon.Add_SysIngredient("Cabbage","","p","5",pLink)
    fcon.Add_SysIngredient("Chicken Broth","","p","5",pLink)
    fcon.Add_SysIngredient("Peppercorn","","p","5",pLink)
    fcon.Add_SysIngredient("Beef Shanks","","p","5",pLink)
    fcon.Add_SysIngredient("Guava","","p","5",pLink)
    fcon.Add_SysIngredient("Kangkong","","p","5",pLink)
    fcon.Add_SysIngredient("Beef Cube","Beef Bouillon","p","5",pLink)
    fcon.Add_SysIngredient("Button Mushroom","","p","5",pLink)
    fcon.Add_SysIngredient("Pechay","","p","5",pLink)
    fcon.Add_SysIngredient("Goat Meat","Goat Head and Feet","p","5",pLink)
    fcon.Add_SysIngredient("Pork Shoulder","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Liver","","p","5",pLink)
    fcon.Add_SysIngredient("Garbanzo Bean","","p","5",pLink)
    fcon.Add_SysIngredient("Egg Yolk","","p","5",pLink)
    fcon.Add_SysIngredient("Tofu","","p","5",pLink)
    fcon.Add_SysIngredient("Tilapia Fillet","","p","5",pLink)
    fcon.Add_SysIngredient("Salmon Fillet","","p","5",pLink)
    fcon.Add_SysIngredient("Coconut","","p","5",pLink)
    fcon.Add_SysIngredient("Sayote","Chayote","p","5",pLink)
    fcon.Add_SysIngredient("Chicken Skin","","p","5",pLink)
    fcon.Add_SysIngredient("Egg White","","p","5",pLink)
    fcon.Add_SysIngredient("Bangus Belly","","p","5",pLink)
    fcon.Add_SysIngredient("Chicken Thigh","","p","5",pLink)
    fcon.Add_SysIngredient("Saba Banana","","p","5",pLink)
    fcon.Add_SysIngredient("Smelt Fish","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Bone","","p","5",pLink)
    fcon.Add_SysIngredient("Beef Bone","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Intestine","","p","5",pLink)
    fcon.Add_SysIngredient("Miki Noodles","","p","5",pLink)
    fcon.Add_SysIngredient("Shrimp Heads/Shells","","p","5",pLink)
    fcon.Add_SysIngredient("Celery Stalk","","p","5",pLink)
    fcon.Add_SysIngredient("White Bread","","p","5",pLink)
    fcon.Add_SysIngredient("Milk","","p","5",pLink)
    fcon.Add_SysIngredient("Ampalaya","Bitter Melon","p","5",pLink)
    fcon.Add_SysIngredient("Mango","","p","5",pLink)
    fcon.Add_SysIngredient("Squid","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Tenderloin","","p","5",pLink)
    fcon.Add_SysIngredient("Pineapple","","p","5",pLink)
    fcon.Add_SysIngredient("Boneless Bangus","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Face","","p","5",pLink)
    fcon.Add_SysIngredient("Pig Brain","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Spare Rib","","p","5",pLink)
    fcon.Add_SysIngredient("Pumpkin","Kalabasa,Calabasa","p","5",pLink)
    fcon.Add_SysIngredient("Lechon Kawali","","p","5",pLink)
    fcon.Add_SysIngredient("Kamote Leaf","","p","5",pLink)
    fcon.Add_SysIngredient("Kamias","","p","5",pLink)
    fcon.Add_SysIngredient("Salmon Belly","","p","5",pLink)
    fcon.Add_SysIngredient("Seafood Soup Base","","p","5",pLink)
    fcon.Add_SysIngredient("Crab Meat","","p","5",pLink)
    fcon.Add_SysIngredient("Corn Kernel","","p","5",pLink)
    fcon.Add_SysIngredient("Imitation Crab","","p","5",pLink)
    fcon.Add_SysIngredient("Chicken Breast","","p","5",pLink)
    fcon.Add_SysIngredient("Sausage","","p","5",pLink)
    fcon.Add_SysIngredient("Pandan Leaf","","p","5",pLink)
    fcon.Add_SysIngredient("Asparagus","","p","5",pLink)
    fcon.Add_SysIngredient("Ube Halaya","","p","5",pLink)
    fcon.Add_SysIngredient("Lechen Flan","","p","5",pLink)
    fcon.Add_SysIngredient("Cremini Mushroom","","p","5",pLink)
    fcon.Add_SysIngredient("Chow Mein Noodles","","p","5",pLink)
    fcon.Add_SysIngredient("Celery","Kinchay","p","5",pLink)
    fcon.Add_SysIngredient("Milkfish","Bangus","p","5",pLink)
    fcon.Add_SysIngredient("Baby Back Ribs","","p","5",pLink)
    fcon.Add_SysIngredient("Honeycomb Tripe","","p","5",pLink)
    fcon.Add_SysIngredient("Ox Feet","","p","5",pLink)
    fcon.Add_SysIngredient("Beef Broth","","p","5",pLink)
    fcon.Add_SysIngredient("Salay Salay Fish","","p","5",pLink)
    fcon.Add_SysIngredient("Beef Chuck Roast","","p","5",pLink)
    fcon.Add_SysIngredient("Chicken Stock","","p","5",pLink)
    fcon.Add_SysIngredient("Fish Ball","","p","5",pLink)
    fcon.Add_SysIngredient("Lemongrass Stalk","","p","5",pLink)
    fcon.Add_SysIngredient("Lemongrass","","p","5",pLink)
    fcon.Add_SysIngredient("Buttermilk","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Butt","","p","5",pLink)
    fcon.Add_SysIngredient("Spinach","","p","5",pLink)
    fcon.Add_SysIngredient("Chicharon","","p","5",pLink)
    fcon.Add_SysIngredient("Smoked Fish","Tinapa","p","5",pLink)
    fcon.Add_SysIngredient("Bottle Gourd","Upo,Calabash","p","5",pLink)
    fcon.Add_SysIngredient("Grape Tomato","","p","5",pLink)
    fcon.Add_SysIngredient("Pear","","p","5",pLink)
    fcon.Add_SysIngredient("Top Round","","p","5",pLink)
    fcon.Add_SysIngredient("Sirloin","","p","5",pLink)
    fcon.Add_SysIngredient("Mozarella Cheese","","p","5",pLink)
    fcon.Add_SysIngredient("Salsa","","p","5",pLink)
    fcon.Add_SysIngredient("Sour Cream","","p","5",pLink)
    fcon.Add_SysIngredient("Yakisoba Noodle","","p","5",pLink)
    fcon.Add_SysIngredient("Chicken Liver","","p","5",pLink)
    fcon.Add_SysIngredient("Cooked Rice","","p","5",pLink)
    fcon.Add_SysIngredient("Beef Sirloin","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Ham","Pigue","p","5",pLink)
    fcon.Add_SysIngredient("Edamame","","p","5",pLink)
    fcon.Add_SysIngredient("Strawberry","","p","5",pLink)
    fcon.Add_SysIngredient("Chicken Feet","","p","5",pLink)
    fcon.Add_SysIngredient("Chicken Wing","","p","5",pLink)
    fcon.Add_SysIngredient("Beef Tripe","","p","5",pLink)
    fcon.Add_SysIngredient("Grouper","Lapu-Lapu","p","5",pLink)
    fcon.Add_SysIngredient("Furikake","","p","5",pLink)
    fcon.Add_SysIngredient("Unsalted Butter","","p","5",pLink)
    fcon.Add_SysIngredient("Spam","","p","5",pLink)
    fcon.Add_SysIngredient("Papaya","","p","5",pLink)
    fcon.Add_SysIngredient("Ube","","p","5",pLink)
    fcon.Add_SysIngredient("Yam","Kamote,Camote","p","5",pLink)
    fcon.Add_SysIngredient("Patola","","p","5",pLink)
    fcon.Add_SysIngredient("Lechon Sauce","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Shank","","p","5",pLink)
    fcon.Add_SysIngredient("Orange Concentrate","","p","5",pLink)
    fcon.Add_SysIngredient("Mango Nectar","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Kidney","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Pancreas","","p","5",pLink)
    fcon.Add_SysIngredient("Orange Juice","","p","5",pLink)
    fcon.Add_SysIngredient("Cassava","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Blood","","p","5",pLink)
    fcon.Add_SysIngredient("Beef Tendon","","p","5",pLink)
    fcon.Add_SysIngredient("Corn Cob","","p","5",pLink)
    fcon.Add_SysIngredient("Quail Egg","","p","5",pLink)
    fcon.Add_SysIngredient("Jumbo Refrigerated Biscuit","","p","5",pLink)
    fcon.Add_SysIngredient("Meatball","","p","5",pLink)
    fcon.Add_SysIngredient("Golden Pompano","","p","5",pLink)
    fcon.Add_SysIngredient("Chicken Cube","Chicken Bouillon","p","5",pLink)
    fcon.Add_SysIngredient("Pandesal Roll","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Rind","","p","5",pLink)
    fcon.Add_SysIngredient("Pig Face","","p","5",pLink)
    fcon.Add_SysIngredient("Snow pea","","p","5",pLink)
    fcon.Add_SysIngredient("Balut","","p","5",pLink)
    fcon.Add_SysIngredient("Chuck Steak","","p","5",pLink)
    fcon.Add_SysIngredient("Red Mung Bean","","p","5",pLink)
    fcon.Add_SysIngredient("Lemon Juice","","p","5",pLink)
    fcon.Add_SysIngredient("Oyster","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Lung","","p","5",pLink)
    fcon.Add_SysIngredient("Mung Bean Sprout","","p","5",pLink)
    fcon.Add_SysIngredient("Luncheon Meat","","p","5",pLink)
    fcon.Add_SysIngredient("Singkamas","Turnip","p","5",pLink)
    fcon.Add_SysIngredient("Tilapia","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Leg","","p","5",pLink)
    fcon.Add_SysIngredient("Lychee Syrup","","p","5",pLink)
    fcon.Add_SysIngredient("Sushi-grade Ahi","","p","5",pLink)
    fcon.Add_SysIngredient("Sigarilyas","","p","5",pLink)
    fcon.Add_SysIngredient("Pan de Leche","","p","5",pLink)
    fcon.Add_SysIngredient("Pandesal Rolls","","p","5",pLink)
    fcon.Add_SysIngredient("Silver Fish","","p","5",pLink)
    fcon.Add_SysIngredient("Pork Ear","","p","5",pLink)
    fcon.Add_SysIngredient("Beef Brisket","","p","5",pLink)
    fcon.Add_SysIngredient("Wonton","","p","5",pLink)
    fcon.Add_SysIngredient("Smoked Round Scad","Galunggong","p","5",pLink)
    fcon.Add_SysIngredient("Pork Heart","","p","5",pLink)
    fcon.Add_SysIngredient("Blue Crab","","p","5",pLink)
    fcon.Add_SysIngredient("Coagulated Blood","","p","5",pLink)
    fcon.Add_SysIngredient("Dashi","","p","5",pLink)
    fcon.Add_SysIngredient("Udon","","p","5",pLink)
    fcon.Add_SysIngredient("Longganisa","","p","5",pLink)
    fcon.Add_SysIngredient("Chicken Drummette","","p","5",pLink)
    fcon.Add_SysIngredient("Beef Neck Bone","","p","5",pLink)
    fcon.Add_SysIngredient("Labong","Bamboo Shoot","p","5",pLink)
    fcon.Add_SysIngredient("Gizzard","","p","5",pLink)
    fcon.Add_SysIngredient("Oxtail","","p","5",pLink)
    fcon.Add_SysIngredient("Frog Leg","","p","5",pLink)



    fcon.Add_SysIngredient("Jelly","","np","",npLink)
    fcon.Add_SysIngredient("Sugar","","np","",npLink)
    fcon.Add_SysIngredient("Water","","np","",npLink)
    fcon.Add_SysIngredient("Condensed Milk","Sweetened Condensed Milk","np","",npLink)
    fcon.Add_SysIngredient("All-Purpose Cream","Table Cream","np","",npLink)
    fcon.Add_SysIngredient("Sago","","np","",npLink)
    fcon.Add_SysIngredient("Rice Flour","","np","",npLink)
    fcon.Add_SysIngredient("Baking Powder","","np","",npLink)
    fcon.Add_SysIngredient("Salt","","np","",npLink)
    fcon.Add_SysIngredient("Cream Cheese","","np","",npLink)
    fcon.Add_SysIngredient("Canola oil","","np","",npLink)
    fcon.Add_SysIngredient("Fish Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Pepper","","np","",npLink)
    fcon.Add_SysIngredient("Paprika","","np","",npLink)
    fcon.Add_SysIngredient("Olive oil","","np","",npLink)
    fcon.Add_SysIngredient("Chorizo de Bilbao","","np","",npLink)
    fcon.Add_SysIngredient("Tomato Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Rice","","np","",npLink)
    fcon.Add_SysIngredient("Saffron","","np","",npLink)
    fcon.Add_SysIngredient("Evaporated Milk","","np","",npLink)
    fcon.Add_SysIngredient("Margarine","","np","",npLink)
    fcon.Add_SysIngredient("Soy Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Mayonnaise","","np","",npLink)
    fcon.Add_SysIngredient("Ground Pepper","","np","",npLink)
    fcon.Add_SysIngredient("Vinegar","Kaong Palm Vinegar","np","",npLink)
    fcon.Add_SysIngredient("Jasmine Rice","","np","",npLink)
    fcon.Add_SysIngredient("Glutinous Rice","","np","",npLink)
    fcon.Add_SysIngredient("Cooking Wine","","np","",npLink)
    fcon.Add_SysIngredient("Sesame Oil","","np","",npLink)
    fcon.Add_SysIngredient("Tablea Chocolate","","np","",npLink)
    fcon.Add_SysIngredient("Tablea de Cacao","","np","",npLink)
    fcon.Add_SysIngredient("Cold Water","","np","",npLink)
    fcon.Add_SysIngredient("Ice","","np","",npLink)
    fcon.Add_SysIngredient("Oyster Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Cornstarch","","np","",npLink)
    fcon.Add_SysIngredient("Coconut Cream","","np","",npLink)
    fcon.Add_SysIngredient("Brown Sugar","","np","",npLink)
    fcon.Add_SysIngredient("Potato","","np","",npLink)
    fcon.Add_SysIngredient("Sweet Potato","","np","",npLink)
    fcon.Add_SysIngredient("Hotdog","","np","",npLink)
    fcon.Add_SysIngredient("Sweet Pickle","Sweet Gherkin Pickle","np","",npLink)
    fcon.Add_SysIngredient("Cheddar Cheese","","np","",npLink)
    fcon.Add_SysIngredient("Flour","","np","",npLink)
    fcon.Add_SysIngredient("Oil","","np","",npLink)
    fcon.Add_SysIngredient("Spring Roll Wrapper","","np","",npLink)
    fcon.Add_SysIngredient("All-Purpose Flour","","np","",npLink)
    fcon.Add_SysIngredient("Baking Soda","","np","",npLink)
    fcon.Add_SysIngredient("Vanilla Extract","","np","",npLink)
    fcon.Add_SysIngredient("Lasagna Noodles","","np","",npLink)
    fcon.Add_SysIngredient("Italian Seasoning","","np","",npLink)
    fcon.Add_SysIngredient("Spaghetti Noodles","","np","",npLink)
    fcon.Add_SysIngredient("Spaghetti Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Quick-melt Cheese","","np","",npLink)
    fcon.Add_SysIngredient("Bay Leaf","","np","",npLink)
    fcon.Add_SysIngredient("Miso Soy Paste","","np","",npLink)
    fcon.Add_SysIngredient("Tamarind Base","","np","",npLink)
    fcon.Add_SysIngredient("Star Anise","","np","",npLink)
    fcon.Add_SysIngredient("Fried Garlic","","np","",npLink)
    fcon.Add_SysIngredient("Corned Beef","","np","",npLink)
    fcon.Add_SysIngredient("Pickle Juice","","np","",npLink)
    fcon.Add_SysIngredient("Tomato Paste","","np","",npLink)
    fcon.Add_SysIngredient("Coffee Granules","","np","",npLink)
    fcon.Add_SysIngredient("Curry Powder","","np","",npLink)
    fcon.Add_SysIngredient("Pineapple Juice","","np","",npLink)
    fcon.Add_SysIngredient("Liver Spread","","np","",npLink)
    fcon.Add_SysIngredient("Olive","Spanish Olive","np","",npLink)
    fcon.Add_SysIngredient("Green agar-agar","","np","",npLink)
    fcon.Add_SysIngredient("Red agar-agar","","np","",npLink)
    fcon.Add_SysIngredient("Coconut Juice","","np","",npLink)
    fcon.Add_SysIngredient("Pandan Extract","","np","",npLink)
    fcon.Add_SysIngredient("Salted Black Beans","Tausi","np","",npLink)
    fcon.Add_SysIngredient("Nata De Coco","","np","",npLink)
    fcon.Add_SysIngredient("Kaong","","np","",npLink)
    fcon.Add_SysIngredient("Light Cream","Table Cream","np","",npLink)
    fcon.Add_SysIngredient("Hot Water","","np","",npLink)
    fcon.Add_SysIngredient("Pizza Dough","","np","",npLink)
    fcon.Add_SysIngredient("Lard","","np","",npLink)
    fcon.Add_SysIngredient("Breadcrumbs","Bread Crumbs","np","",npLink)
    fcon.Add_SysIngredient("Bagoong","Shrimp Paste","np","",npLink)
    fcon.Add_SysIngredient("Garlic Powder","","np","",npLink)
    fcon.Add_SysIngredient("Shallot","","np","",npLink)
    fcon.Add_SysIngredient("MSG","","np","",npLink)
    fcon.Add_SysIngredient("Rock Salt","","np","",npLink)
    fcon.Add_SysIngredient("Rock Pepper","","np","",npLink)
    fcon.Add_SysIngredient("Tuna Flakes","","np","",npLink)
    fcon.Add_SysIngredient("Sardines","","np","",npLink)
    fcon.Add_SysIngredient("Arrowroot Starch","","np","",npLink)
    fcon.Add_SysIngredient("Worcestershire Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Pineapple Chunks","","np","",npLink)
    fcon.Add_SysIngredient("Active Dry Yeast","","np","",npLink)
    fcon.Add_SysIngredient("Powdered Milk","","np","",npLink)
    fcon.Add_SysIngredient("Sotanghon","Cellophane Noodles","np","",npLink)
    fcon.Add_SysIngredient("Chinese Wine","","np","",npLink)
    fcon.Add_SysIngredient("Crab and Corn Mix","","np","",npLink)
    fcon.Add_SysIngredient("Vegetable Oil","","np","",npLink)
    fcon.Add_SysIngredient("Gulaman Cube","","np","",npLink)
    fcon.Add_SysIngredient("Sweetened Bean","","np","",npLink)
    fcon.Add_SysIngredient("Macapuno","","np","",npLink)
    fcon.Add_SysIngredient("Shaved Ice","","np","",npLink)
    fcon.Add_SysIngredient("Ice Cream","","np","",npLink)
    fcon.Add_SysIngredient("Sesame Seed","","np","",npLink)
    fcon.Add_SysIngredient("Red Pepper Flake","","np","",npLink)
    fcon.Add_SysIngredient("Sriracha Chili Sauce","","np","",npLink)
    fcon.Add_SysIngredient("White Wine","","np","",npLink)
    fcon.Add_SysIngredient("Sweet Chili Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Vegetable Shortening","","np","",npLink)
    fcon.Add_SysIngredient("Danggit","","np","",npLink)
    fcon.Add_SysIngredient("Tamarind Powder","","np","",npLink)
    fcon.Add_SysIngredient("Bihon","Rice Noodles","np","",npLink)
    fcon.Add_SysIngredient("Sweet Soy Sauce","Kecap Manis","np","",npLink)
    fcon.Add_SysIngredient("Roasted Peanuts","","np","",npLink)
    fcon.Add_SysIngredient("Lomi Noodles","","np","",npLink)
    fcon.Add_SysIngredient("Graham Cracker Crumbs","","np","",npLink)
    fcon.Add_SysIngredient("Ground Coriander","","np","",npLink)
    fcon.Add_SysIngredient("Raw Peanuts","","np","",npLink)
    fcon.Add_SysIngredient("Cinnamon Stick","","np","",npLink)
    fcon.Add_SysIngredient("Dried Chili","","np","",npLink)
    fcon.Add_SysIngredient("Dry Mung Beans","Munggo","np","",npLink)
    fcon.Add_SysIngredient("Banana Ketchup","","np","",npLink)
    fcon.Add_SysIngredient("Cheese","","np","",npLink)
    fcon.Add_SysIngredient("Salted Duck","","np","",npLink)
    fcon.Add_SysIngredient("Cocoa","","np","",npLink)
    fcon.Add_SysIngredient("Rice Vinegar","","np","",npLink)
    fcon.Add_SysIngredient("Chili Powder","","np","",npLink)
    fcon.Add_SysIngredient("Cumin","","np","",npLink)
    fcon.Add_SysIngredient("Short-grain Rice","","np","",npLink)
    fcon.Add_SysIngredient("Rice Noodle Stick","","np","",npLink)
    fcon.Add_SysIngredient("Hot Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Chili Paste","","np","",npLink)
    fcon.Add_SysIngredient("Fruit Cocktail","","np","",npLink)
    fcon.Add_SysIngredient("Condensed Cream of Mushroom Soup","","np","",npLink)
    fcon.Add_SysIngredient("Wonton Wrapper","","np","",npLink)
    fcon.Add_SysIngredient("Black Pepper","","np","",npLink)
    fcon.Add_SysIngredient("Chili Garlic Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Atchuete Powder","Atsuete Powder","np","",npLink)
    fcon.Add_SysIngredient("Elbow Macaroni","","np","",npLink)
    fcon.Add_SysIngredient("Apple Cider Vinegar","","np","",npLink)
    fcon.Add_SysIngredient("Sweet Pickle Relish","","np","",npLink)
    fcon.Add_SysIngredient("Black Olive","","np","",npLink)
    fcon.Add_SysIngredient("Cherry","","np","",npLink)
    fcon.Add_SysIngredient("Liquid Mango Flavoring","","np","",npLink)
    fcon.Add_SysIngredient("Cream of Tartar","","np","",npLink)
    fcon.Add_SysIngredient("Cocoa Powder","","np","",npLink)
    fcon.Add_SysIngredient("Nutella","","np","",npLink)
    fcon.Add_SysIngredient("Liquid Pandan Extract","","np","",npLink)
    fcon.Add_SysIngredient("Pineapple Tidbits","","np","",npLink)
    fcon.Add_SysIngredient("Raisin","","np","",npLink)
    fcon.Add_SysIngredient("Red Food Coloring","","np","",npLink)
    fcon.Add_SysIngredient("Unflavored Gelatin","","np","",npLink)
    fcon.Add_SysIngredient("Cashew","","np","",npLink)
    fcon.Add_SysIngredient("Honey","","np","",npLink)
    fcon.Add_SysIngredient("Velvetta Cheese","","np","",npLink)
    fcon.Add_SysIngredient("Fusilli Pasta","","np","",npLink)
    fcon.Add_SysIngredient("Cinnamon","","np","",npLink)
    fcon.Add_SysIngredient("Almond Extract","","np","",npLink)
    fcon.Add_SysIngredient("Buko Pandan Flavor Extract","","np","",npLink)
    fcon.Add_SysIngredient("Heavy Cream","","np","",npLink)
    fcon.Add_SysIngredient("Nori Seaweed","","np","",npLink)
    fcon.Add_SysIngredient("Turmeric","","np","",npLink)
    fcon.Add_SysIngredient("Miswa","Rice Vermicelli","np","",npLink)
    fcon.Add_SysIngredient("Light Syrup","","np","",npLink)
    fcon.Add_SysIngredient("Molasses","","np","",npLink)
    fcon.Add_SysIngredient("Brandy","","np","",npLink)
    fcon.Add_SysIngredient("Nutmeg","","np","",npLink)
    fcon.Add_SysIngredient("Allspice","","np","",npLink)
    fcon.Add_SysIngredient("Barbecue Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Mirin","","np","",npLink)
    fcon.Add_SysIngredient("Sake","","np","",npLink)
    fcon.Add_SysIngredient("Ube Extract","","np","",npLink)
    fcon.Add_SysIngredient("Langka Extract","","np","",npLink)
    fcon.Add_SysIngredient("Strawberry Jam","","np","",npLink)
    fcon.Add_SysIngredient("Seasoning Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Dulce de Leche","","np","",npLink)
    fcon.Add_SysIngredient("Lye Water","","np","",npLink)
    fcon.Add_SysIngredient("Ube Food Coloring","","np","",npLink)
    fcon.Add_SysIngredient("Gin","","np","",npLink)
    fcon.Add_SysIngredient("Rum","","np","",npLink)
    fcon.Add_SysIngredient("Chinese five-spice powder","","np","",npLink)
    fcon.Add_SysIngredient("Bean Curd Sheet","","np","",npLink)
    fcon.Add_SysIngredient("Magic Sarap Seasoning Powder","","np","",npLink)
    fcon.Add_SysIngredient("Orange Food Coloring Powder","","np","",npLink)
    fcon.Add_SysIngredient("Unflavored Jelly Mix","","np","",npLink)
    fcon.Add_SysIngredient("Chocolate Chip","","np","",npLink)
    fcon.Add_SysIngredient("Siomai Wrapper","Shumai Wrapper","np","",npLink)
    fcon.Add_SysIngredient("Hoisin Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Simple Syrup","","np","",npLink)
    fcon.Add_SysIngredient("Kosher Salt","","np","",npLink)
    fcon.Add_SysIngredient("Ground Peanut","","np","",npLink)
    fcon.Add_SysIngredient("Egg Roll Wrapper","","np","",npLink)
    fcon.Add_SysIngredient("Arnibal Syrup","","np","",npLink)
    fcon.Add_SysIngredient("Banana Essence","","np","",npLink)
    fcon.Add_SysIngredient("Liquid Seasoning","","np","",npLink)
    fcon.Add_SysIngredient("Turmeric Powder","","np","",npLink)
    fcon.Add_SysIngredient("Annato Seed","","np","",npLink)
    fcon.Add_SysIngredient("Water Chestnut","","np","",npLink)
    fcon.Add_SysIngredient("Plum Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Walnut","","np","",npLink)
    fcon.Add_SysIngredient("Dried Oregano","","np","",npLink)
    fcon.Add_SysIngredient("Dried Basil","","np","",npLink)
    fcon.Add_SysIngredient("Cake Flour","","np","",npLink)
    fcon.Add_SysIngredient("7-Up","","np","",npLink)
    fcon.Add_SysIngredient("Ube Jam","","np","",npLink)
    fcon.Add_SysIngredient("Violet Food Color","","np","",npLink)
    fcon.Add_SysIngredient("Powdered Sugar","","np","",npLink)
    fcon.Add_SysIngredient("Annatto Powder","","np","",npLink)
    fcon.Add_SysIngredient("Peanut Butter","","np","",npLink)
    fcon.Add_SysIngredient("Cornstarch Noodles","","np","",npLink)
    fcon.Add_SysIngredient("Macadamia Nut","","np","",npLink)
    fcon.Add_SysIngredient("Sushi Rice","","np","",npLink)
    fcon.Add_SysIngredient("Instant Coffee","","np","",npLink)
    fcon.Add_SysIngredient("Dilis","Anchovy","np","",npLink)
    fcon.Add_SysIngredient("Dried Ancho Chili","","np","",npLink)
    fcon.Add_SysIngredient("Dried Guajillo Chili","","np","",npLink)
    fcon.Add_SysIngredient("Dried Oregano","","np","",npLink)
    fcon.Add_SysIngredient("Ground Clove","","np","",npLink)
    fcon.Add_SysIngredient("Tapioca Flour","","np","",npLink)
    fcon.Add_SysIngredient("Tonkatsu Sauce","","np","",npLink)
    fcon.Add_SysIngredient("Pinipig","Pinpig","np","",npLink)
    fcon.Add_SysIngredient("Femented Tofu","Fermented Bean Curd,Square Tahure","np","",npLink)
    fcon.Add_SysIngredient("Sprite","","np","",npLink)
    fcon.Add_SysIngredient("Dark Beer","","np","",npLink)
    fcon.Add_SysIngredient("Instant Pancit Canton","","np","",npLink)
    fcon.Add_SysIngredient("Anisado Wine","","np","",npLink)
    fcon.Add_SysIngredient("Hog Casing","","np","",npLink)
    fcon.Add_SysIngredient("Dry Sherry","","np","",npLink)
    fcon.Add_SysIngredient("Ice Cube","","np","",npLink)
    fcon.Add_SysIngredient("Saluyot","","np","",npLink)
    fcon.Add_SysIngredient("Panutsa Syrup","","np","",npLink)
    fcon.Add_SysIngredient("Pectin","","np","",npLink)

    print("> Finished Adding Valid Ingredients")
    return

main()

# remove all special characters if any, remove spaces
# 1. check if all letters is present. how much percent does the characters appear on the actual recipe ingredient
# check for sequence, every right character sequence is scored



# 1. Sa bawat ingredient na galing sa recipe, kukuha tayo ng mga ingredients galing sa inventory. 
# 2. in order to know yung similarities o malamn kung ano ang kukunin, yung ingredient from both sides dapat matangal ang special characters at spaces. 
# 3. yung direction ng comparison is from recipe to inventory. pag nasabi na Canola Oil at walang canola oil sa inventory, most likely ay yung Oil ang magagamit for comparison and it is expected na di lang maari isa ang mapagkunan. 
# 4. pag wala talaga nakuhang comparison, kunware egg lang ang nasa inventory, walang points o score na makukuha. 

# makakakuha ng score yung recipe sa availability ng items sa inventory. 

