choosedRecipes = ['Avocado Sago Jelly',
    'Bibingka',
    'Champorado',
    'Ginisang Sayote',
    'Ginataang Puso ng Saging',
    'Paella','Lumpiang Ubod','Ginisang Togue','Kilawing Puso ng Saging','Champorado','Minatamis na Langka','Shrimp with Oyster Sauce',
    'Chicken Afritada','Morcon','Fried Okra','Suman Malagkit with Coconut Caramel Sauce','Filipino-style Lasagna','Instant Pot Filipino-style Spaghetti',
    'Filipino Scrambled Eggs','Lengua Estofado','Sinigang na Hito sa Miso','Ginisang Repolyo','Sinigang na Baka sa Bayabas','Ginisang Pechay with Oyster Sauce',
    'Tokwa’t Baboy with Tausi','Sweet and Sour Fish','Buko Pandan Salad','Ginisang Sayote','Baked Cheese Shrimp','Chicken Skin Chicharon','Ginisang Sayote with Chicken',
    'Banana Turon','Binagoongan Fried Rice','Lugaw at Tokwa','La Paz Batchoy','Crispy Tuna Shanghai','Puto Maya and Sikwate','Adobong Talong','Sisig Pusit',
    'Sweet and Sour Pork','Brazo de Mercedes','Monay','Kinamatisang Baboy','Pastillas de Leche',
    'Pinakbet with Crispy Lechon','Crispy Sisig','Ensaladang Pipino','Sinaing na Tulingan','Crab and Corn Soup','Ginataang Gulay','Taho','Crispy Tahong (Deep-Fried Mussels)',
    'Chicken and Pork Adobo','Halo-Halo','Lengua de Gato','Paksiw na Bangus','Loslos',
    'Instant Pot Chicken Adobo','Grilled Tuna Belly','Ginataang Langka at Danggit','Kilawing Labanos at Baboy','Beef Curry','Corned Beef Spaghetti',
    'Miki Bihon','Pancit Lomi Guisado','Graham Balls','Lechon Kawali','Lemongrass Roasted Chicken','Ginataang Munggo at Baboy','Ginisang Munggo at Chicharon',
    'Sotanghon at Upo Soup','Ginataang Talong','Adobong Itlog','Pork Adobo with Pineapple','Slow Cooker Lechon','Beef Afritada','Humba','Adobo sa Gata','Pancit Malabon',
    'Crispy Chicken Livers a la Bistek','Tinapa Fried Rice','Inihaw na Pusit (Grilled Squid)','Homemade Holiday Ham','Adobong Paa nang Manok (Chicken Feet Adobo)','Goto',
    'Beef Tapa','Sushi Bake','Chicken a la King','Pineapple Pork Ribs','Siopao Bola-Bola','Siopao Asado','Escabeche Lapu Lapu',
    'Chicken Inasal','Chicken Adobo','Lumpiang Sariwa','Ukoy','Leche Flan','Chicken Adobo with Liver Spread','Pork Estofado','Adobong Manok sa Patis','Chicken Caldereta',
    'Maja Blanca Espesyal','Paksiw na Lechon','Lechon Manok','Inihaw na Liempo','Sizzling Tofu','Batsui','Chicken Tapa','Chicken Bistek',
    'Pork Pochero','Dinuguan','Pininyahang Manok','Ginataang Hipon','Ginataang Kalabasa, Sitaw at Hipon','Nilagang Baka','Adobong Sitaw with Pork','Laing',
    'Bangus sa Tausi','Pork Siomai','Bicol Express','Pata Hamonado','Pork Chicharon','Pininyahang Baboy','Pork Afritada','Sizzling Sisig','Chicken Sopas',
    'Pork Menudo','Chicken Pastel','Chicken Sisig','Biko','Binagoongan Baboy','Yema Cake','Filipino Pork Barbecue','Chicken Kare-Kare','Filipino-style Fried Chicken',
    'Bopis','Dulce de Leche FLan','Chicken Bicol Express','Pancit Bihon Guisado','Pata Tim','Lumpiang Hubad','Sinigang na Salmon Belly sa Kamias','Lumpia Shanghai',
    'Burger Steak','Baby Back Ribs with Adobo Glaze','Pork Embutido','Ginataang Sigarilyas at Kalabasa','Ginisang Sardinas at Miswa','Beef Pares','Pork Bistek',
    'Kare-kareng Pata','Kutsinta','Filipino Beef Tapa','Chop Suey with Tofu and Shiitake Mushrooms','Salt and Pepper Pork Chops','Ginataang Seafood','Laswa',
    'Sinigang na Baka','Pancit Canton','Batchoy Tagalog','Beef Salpicao','Chicken Tocino','Nilagang Baboy','Buchi','Longganisa','Spicy Tahong','Adobong Kangkong',
    'Tokwa’t Baboy','Beef Mechado','Relyenong Bangus','Tortang Talong','Camaron Rebosado','Chicken Pochero','Bulalo','Arroz Caldo','Bagis','Chop Suey','Pinakbet Tagalog',
    'Tinolang Manok (Chicken Tinola)','Pork Adobo','Sinigang na Baboy']

print("Number of Recipes: "+str(len(choosedRecipes)))